name: Build Application

on:  
  push:
    branches:
      - '**'

jobs:
  build-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform fmt
      id: fmt
      run: terraform -chdir=terraform/ fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform -chdir=terraform/ init

    - name: Terraform Validate
      id: validate
      run: terraform -chdir=terraform/ validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform -chdir=terraform/ plan -no-color

  build-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
