name: Deploy Application and Infrastructure

on:
  workflow_run:
    workflows: ["Build Application"]
    types:
      - completed
    branches:
      - devel
      - stage
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - uses: actions/download-artifact@v4
      with:
        name: infra-artifact
        path: terraform/

    - name: Terraform Init
      id: init
      run: terraform -chdir=terraform/ init

    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: cristobalzuluaga
        minimum-approvals: 1
        issue-title: "Deploying Infra to AWS"
        issue-body: "Please approve or deny the deployment"
        exclude-workflow-initiator-as-approver: false

    - name: Terraform Apply
      id: apply
      run: terraform -chdir=terraform/ apply tfplan -no-color 

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
    - name: Display structure of downloaded files
      run: ls -R
